const property = [
    {
      imageUrl: "",
      imageAlt: "image here",
      name: "xyz",
      lastUpdated: "20/10/2021",
      lessons: 1,
      minutes: 13,
      tag: "Marketing",
      status: "live",
    },
    {
      // imageUrl: "https://bit.ly/2Z4KKcF",
      imageAlt: "image here",
      name: "xyz",
      lastUpdated: "20/10/2021",
      lessons: 1,
      minutes: 13,
      tag: "Marketing",
      status: "draft",
    },
    {
      // imageUrl: "https://bit.ly/2Z4KKcF",
      imageAlt: "image here",
      name: "xyz",
      lastUpdated: "20/10/2021",
      lessons: 1,
      minutes: 13,
      tag: "Marketing",
      status: "archived",
    },
    {
      // imageUrl: "https://bit.ly/2Z4KKcF",
      imageAlt: "image here",
      name: "xyz",
      lastUpdated: "20/10/2021",
      lessons: 1,
      minutes: 13,
      tag: "Marketing",
      status: "live",
    },
    {
      // imageUrl: "https://bit.ly/2Z4KKcF",
      imageAlt: "image here",
      name: "xyz",
      lastUpdated: "20/10/2021",
      lessons: 1,
      minutes: 13,
      tag: "Marketing",
      status: "draft",
    },
    {
      // imageUrl: "https://bit.ly/2Z4KKcF",
      imageAlt: "image here",
      name: "xyz",
      lastUpdated: "20/10/2021",
      lessons: 1,
      minutes: 13,
      tag: "Marketing",
      status: "live",
    },
    
  ];

  export default property;